In [53]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [54]:
vector1 = np.arange(1, 11)

In [4]:
print(vector1)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [5]:
matrix2 = np.zeros((3, 3), dtype=float)

In [6]:
print (matrix2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [7]:
matrix3 = np.random.randint(1, 11, size=(5, 5))

In [8]:
print (matrix3)

[[ 2  4  4  7  3]
 [ 8  5  7  2  2]
 [ 7  3  9  2  9]
 [ 6  8  8  8  8]
 [10  3  2  3  6]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [9]:
matrix4 = np. random.rand(4, 4)

In [10]:
print(matrix4)

[[0.73970524 0.21174919 0.73933551 0.26726954]
 [0.16774618 0.99252201 0.51420123 0.01647522]
 [0.41142097 0.02149425 0.53331552 0.40640624]
 [0.51877519 0.70014942 0.45576798 0.22674941]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [11]:
vector5_1 = np.random.randint(1, 11, size=5)

In [12]:
vector5_2 = np.random.randint(1, 11, size=5)

In [13]:
print (vector5_1)

[4 2 1 9 5]


In [14]:
print (vector5_2)

[3 1 5 1 7]


In [15]:
print (vector5_1+vector5_2)

[ 7  3  6 10 12]


In [16]:
print (vector5_1-vector5_2)

[ 1  1 -4  8 -2]


In [17]:
print (vector5_1*vector5_2)

[12  2  5  9 35]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [18]:
vector6_1 = np.random.rand(7)

In [19]:
vector6_2 = np.random.rand(7)

In [20]:
print(np.dot(vector6_1, vector6_2))

1.9126600804620757


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [21]:
matrix7_1 = np.random.randint(1, 11, size=(2,2))

In [22]:
matrix7_2 = np.random.randint(1, 11, size=(2,3))

In [23]:
print(np.dot(matrix7_1, matrix7_2))

[[ 51 117 111]
 [ 73 102  86]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [24]:
matrix8 = np.random.randint(1, 11, size=(3,3))

In [25]:
vector8_inv = np.linalg.inv(matrix8)

In [26]:
print(matrix8)

[[ 3 10  9]
 [ 2 10  5]
 [10 10  4]]


In [27]:
print(vector8_inv)

[[ 0.03030303 -0.15151515  0.12121212]
 [-0.12727273  0.23636364 -0.00909091]
 [ 0.24242424 -0.21212121 -0.03030303]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [28]:
matrix9 = np.random.rand(4,4)

In [29]:
print(np.transpose(matrix9))

[[0.97526032 0.11940125 0.60313988 0.92296742]
 [0.70766587 0.47674745 0.02633816 0.46025425]
 [0.36903074 0.25834487 0.12060524 0.36510639]
 [0.49388357 0.6283031  0.71882641 0.69784485]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [30]:
matrix10 = np.random.randint(1, 11, size=(3,4))

In [31]:
vector10 = np.random.randint(1,11, size = 4)

In [32]:
print(np.dot(matrix10, vector10))

[ 65 129  62]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [33]:
matrix11 = np.random.rand(2,3)

In [34]:
vector11 = np.random.rand(3)

In [35]:
print(np.dot(matrix11, vector11))

[0.89037183 0.81512856]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [36]:
matrix12_1 = np.random.randint(1, 11, size=(2,2))

In [37]:
matrix12_2 = np.random.randint(1, 11, size=(2,2))

In [38]:
print(np.multiply(matrix12_1, matrix12_2))

[[ 9 63]
 [15 54]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [39]:
matrix13_1 = np.random.rand(2,2)

In [40]:
matrix13_2 = np.random.rand(2,2)

In [41]:
print(np.matmul(matrix13_1, matrix13_2))

[[0.80036392 0.16685434]
 [0.52375149 0.24513949]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [42]:
matrix14 = np.random.randint(1, 101, size=(5,5))

In [43]:
print(matrix14.sum())

1139


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [44]:
matrix15_1 = np.random.randint(1, 11, size=(4,4))

In [45]:
matrix15_2 = np.random.randint(1, 11, size=(4,4))

In [46]:
print(np.subtract(matrix15_1, matrix15_2))

[[ 5 -4 -1  6]
 [-2 -4  4  8]
 [ 1  5  0 -4]
 [ 2  8  8  4]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [47]:
matrix16 = np.random.rand(3,3)

In [48]:
print(np.sum(matrix16, axis=0))

[0.97464865 0.97552451 1.58576012]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [49]:
matrix17 = np.random.randint(1, 100, size=(3, 4))

In [50]:
print(np.square(matrix17))

[[   1 2209 3364 6724]
 [ 121 7921  289 3136]
 [ 100 1156 9025  900]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [51]:
vector18 = np.random.randint(1, 51, size = 4)

In [52]:
print(np.sqrt(vector18))

[4.58257569 5.         3.87298335 6.164414  ]
