In [2]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [5]:
vector1 = np.arange(1, 11)

In [ ]:
print(vector1)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [ ]:
matrix2 = np.zeros((3, 3), dtype=float)

In [ ]:
print (matrix2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
matrix3 = np.random.randint(1, 11, size=(5, 5))

In [ ]:
print (matrix3)

[[5 2 9 7 8]
 [5 3 8 8 2]
 [7 2 7 6 5]
 [8 9 9 4 8]
 [9 9 2 3 5]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
matrix4 = np. random.rand(4, 4)

In [ ]:
print(matrix4)

[[0.78676677 0.13809374 0.56708733 0.58915984]
 [0.2001976  0.57562302 0.82447668 0.99628033]
 [0.29478713 0.54532862 0.79145205 0.30524119]
 [0.48789507 0.98118442 0.23083649 0.41926402]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
vector5_1 = np.random.randint(1, 11, size=5)

In [ ]:
vector5_2 = np.random.randint(1, 11, size=5)

In [ ]:
print (vector5_1)

[ 9  7 10 10  2]


In [ ]:
print (vector5_2)

[9 1 2 6 9]


In [ ]:
print (vector5_1+vector5_2)

[18  8 12 16 11]


In [ ]:
print (vector5_1-vector5_2)

[ 0  6  8  4 -7]


In [ ]:
print (vector5_1*vector5_2)

[81  7 20 60 18]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
vector6_1 = np.random.rand(7)

In [ ]:
vector6_2 = np.random.rand(7)

In [ ]:
print(np.dot(vector6_1, vector6_2))

7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
matrix7_1 = np.random.randint(1, 11, size=(2,2))

In [ ]:
matrix7_2 = np.random.randint(1, 11, size=(2,3))

In [ ]:
print(np.dot(matrix7_1, matrix7_2))

8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [ ]:
matrix8 = np.random.randint(1, 11, size=(3,3))

In [ ]:
vector8_inv = np.linalg.inv(matrix8)

In [ ]:
print(matrix8)

[[8 6 8]
 [3 3 5]
 [8 6 2]]


In [ ]:
print(vector8_inv)

[[ 0.66666667 -1.         -0.16666667]
 [-0.94444444  1.33333333  0.44444444]
 [ 0.16666667 -0.         -0.16666667]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [ ]:
matrix9 = np.random.rand(4,4)

In [ ]:
print(np.transpose(matrix9))

[[0.81160575 0.00320169 0.95420123 0.52632624]
 [0.59399896 0.91517892 0.69426668 0.06929925]
 [0.85856646 0.55755972 0.97951798 0.97752508]
 [0.86349635 0.90496848 0.11880838 0.05881808]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [ ]:
matrix10 = np.random.randint(1, 11, size=(3,4))

In [ ]:
vector10 = np.random.randint(1,11, size = 4)

In [ ]:
print(np.dot(matrix10, vector10))

[108  70  84]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [ ]:
matrix11 = np.random.rand(2,3)

In [ ]:
vector11 = np.random.rand(3)

In [ ]:
print(np.dot(matrix11, vector11))

[0.43819984 0.17392658]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [ ]:
matrix12_1 = np.random.randint(1, 11, size=(2,2))

In [ ]:
matrix12_2 = np.random.randint(1, 11, size=(2,2))

In [ ]:
print(np.multiply(matrix12_1, matrix12_2))

[[54  9]
 [10 36]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [ ]:
matrix13_1 = np.random.rand(2,2)

In [ ]:
matrix13_2 = np.random.rand(2,2)

In [ ]:
print(np.matmul(matrix13_1, matrix13_2))

[[0.22908377 0.70320657]
 [0.09905071 0.30010899]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [ ]:
matrix14 = np.random.randint(1, 101, size=(5,5))

In [ ]:
print(matrix14.sum())

1358


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [ ]:
matrix15_1 = np.random.randint(1, 11, size=(4,4))

In [ ]:
matrix15_2 = np.random.randint(1, 11, size=(4,4))

In [ ]:
print(np.subtract(matrix15_1, matrix15_2))

[[ 4  4  2  2]
 [-8  3  3 -6]
 [-2 -5  6 -8]
 [ 2  0 -1 -6]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [ ]:
matrix16 = np.random.rand(3,3)

In [ ]:
print(np.sum(matrix16, axis=0))

[1.13782174 1.37221235 1.09419169]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [ ]:
matrix17 = np.random.randint(1, 100, size=(3, 4))

In [ ]:
print(np.square(matrix17))

[[  16  484  196 9409]
 [1849 9216 3249   81]
 [1369 2809 1225 1024]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [ ]:
vector18 = np.random.randint(1, 51, size = 4)

In [ ]:
print(np.sqrt(vector18))

[7.         6.8556546  6.40312424 2.        ]
